version: '3.3'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    hostname: mariadb
    restart: always
    volumes:
      - volume-mariadb:/var/lib/mysql
    networks:
      - Inception
    env_file:
      - .env

  wordpress:
    container_name: wp
    build: ./requirements/wordpress
    restart: always
    volumes:
      - volume-wordpress:/var/www/html
    networks:
      - Inception
    depends_on:
      - mariadb
    env_file:
      - .env

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    restart: always
    volumes:
      - volume-wordpress:/var/www/html
    networks:
      - Inception
    depends_on:
      - wordpress
    env_file:
      - .env
    extra_hosts:
      - "jvigneau.42.fr:127.0.0.1"

networks:
  Inception:
    driver: bridge

volumes:
  volume-mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/jvigneau/data/mariadb

  volume-wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/jvigneau/data/wordpress