CREATE DATABASE IF NOT EXISTS ${WP_BD};

CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_USERPASS}';

GRANT ALL PRIVILEGES ON ${WP_DB}.* TO ${DB_USER} IDENTIFIED BY '${DB_USERPASS}';

ALTER USER 'root'@'localhost' IDENTIFIED BY '${DB_ROOTPASS}';

FLUSH PRIVILEGES;